services:

  postgres:
    image: postgres:16
    container_name: transaction-postgres

    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yash8252

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: transaction-redis


  api:
    build: .

    container_name: transaction-api

    depends_on:
      - postgres
      - redis

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - ./uploads:/app/uploads

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

  worker:
    build: .

    container_name: transaction-worker

    depends_on:
      - postgres
      - redis

    env_file:
      - .env

    volumes:
      - ./uploads:/app/uploads

    command: >
      celery
      -A app.workers.celery_app
      worker
      --loglevel=info

volumes:

  postgres_data: